version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  postgres-db:
    image: postgres:17
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

volumes:
  pgdata:
    name: pgdata

networks:
  app-network:
    driver: bridge